using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.Tilemaps;

[System.Serializable]
public class ResourceData 
{
    public GameObject obj;
    public int health;
    public int amountGiven;
    public int resourceID;
}

[System.Serializable]
public class VeinData
{
    public ResourceType type;
    public int[] resourceDataID;
}

public class ResourceSystem : MonoBehaviour
{
    public static ResourceSystem instance {get; private set;}
    public ResourceData[] resources;
    public VeinData[] veins;
    public Dictionary<Vector3Int, ResourceData> resourcesData = new Dictionary<Vector3Int, ResourceData>();

    [Header("Spawning Resources")]
    public Tilemap spawnedStructures; //Generated by Computer
    public Tilemap builtStructures; //Built by player
    
    public int height;
    public int width;
    public int offsetHeight;
    public int offsetWidth;

    public int minResources = 10; //To avoid a completely empty world
    public int veinWidth;
    public int veinHeight;
    public float veinChance; //To Spawn a vein
    public int veinOreChance; //For Individual Ores to spawn inside a vein
    public float resourceChance = 15f;

    [Header("Refilling Resources")]
    public int distanceFromPlayer = 20;
    public int minimumToRefill = 100;


    void Awake()
    {
        instance = this;
    }

    void Start()
    {
        ScatterResources(false);
    }

    void Update()
    {
        if(Input.GetKeyDown(KeyCode.R))
        {
            Refill();
        }
    }

    void ScatterResources(bool checkDistance)
    {
        resourcesData.Clear();
        for(int x = offsetWidth; x < width + offsetWidth; x++)
        {
            for(int y = offsetHeight; y < height + offsetHeight; y++)
            {
                Vector3Int newPos = new Vector3Int(x, y, 0);
                Vector2 checkPos = new Vector2(newPos.x, newPos.y);
                if(checkDistance && Vector2.Distance(checkPos, Settings.instance.player.position) < distanceFromPlayer)
                {
                    continue;
                }

                bool alreadyExists = spawnedStructures.GetTile(newPos) != null || builtStructures.GetTile(newPos) != null;

                if(alreadyExists)
                {
                    continue;
                }

                float chance = Random.Range(0, 100f);
                if(chance <= resourceChance)
                {
                    if(chance <= veinChance)
                    {
                        SpawnVein(newPos);
                    }
                    else
                    {
                        SpawnResource(newPos);
                    }
                }
            }
        }

        if(resourcesData.Count < minResources)
        {
            int leftToGenerate = minResources - resourcesData.Count;

            while(leftToGenerate > 0)
            {
                int randomX = Random.Range(offsetWidth, width + offsetWidth + 1);
                int randomY = Random.Range(offsetHeight, height + offsetHeight + 1);

                Vector3Int newPos = new Vector3Int(randomX, randomY, 0);
                Vector2 checkPos = new Vector2(newPos.x, newPos.y);
                if(checkDistance && Vector2.Distance(checkPos, Settings.instance.player.position) < distanceFromPlayer)
                {
                    continue;
                }

                bool alreadyExists = spawnedStructures.GetTile(newPos) != null || builtStructures.GetTile(newPos) != null || resourcesData.ContainsKey(newPos);

                if(alreadyExists)
                {
                    continue;
                }

                float chance = Random.Range(0, 100f);
                if(chance <= veinChance)
                {
                    SpawnVein(newPos);
                }
                else
                {
                    SpawnResource(newPos);
                }
                leftToGenerate--;
            }
        }
    }

    void Refill()
    {
        Debug.Log(resourcesData.Count);

        if(resourcesData.Count > minimumToRefill)
        {
            return;
        }

        ScatterResources(true);
    }

    void SpawnResource(Vector3Int pos)
    {
        int randomResource = Random.Range(0, resources.Length);
        Vector3 correctedPos = new Vector3(pos.x + 0.5f, pos.y + 0.5f, 0f);

        GameObject go = Instantiate(resources[randomResource].obj, correctedPos, Quaternion.identity);

        resourcesData.Add(pos, new ResourceData {obj = go, 
            health = resources[randomResource].health, 
            amountGiven = resources[randomResource].amountGiven,
            resourceID = resources[randomResource].resourceID});
    }

    void SpawnVein(Vector3Int pos)
    {
        int times = 0;
        int veinID = Random.Range(0, veins.Length);
        for(int x = 0; x < veinWidth; x++)
        {
            for(int y = 0; y < veinHeight; y++)
            {
                Vector3Int veinPos = new Vector3Int(pos.x + x, pos.y + y, 0);

                bool alreadyExists = spawnedStructures.GetTile(veinPos) != null || builtStructures.GetTile(veinPos) != null || resourcesData.ContainsKey(veinPos);

                if(alreadyExists)
                {
                    continue;
                }

                float chance = Random.Range(0, 100f);
                if(chance <= veinOreChance || times == 0)
                {
                    SpawnVeinResource(veinPos, veinID);
                    times++;
                }
            }
        }
    }

    void SpawnVeinResource(Vector3Int pos, int veinID)
    {
        int randomResource = Random.Range(0, veins[veinID].resourceDataID.Length);
        GameObject randomObj = resources[veins[veinID].resourceDataID[randomResource]].obj;
        Vector3 correctedPos = new Vector3(pos.x + 0.5f, pos.y + 0.5f, 0f);

        GameObject go = Instantiate(resources[veins[veinID].resourceDataID[randomResource]].obj, correctedPos, Quaternion.identity);

        resourcesData.Add(pos, new ResourceData {obj = go, 
            health = resources[veins[veinID].resourceDataID[randomResource]].health, 
            amountGiven = resources[veins[veinID].resourceDataID[randomResource]].amountGiven,
            resourceID = resources[veins[veinID].resourceDataID[randomResource]].resourceID});
    }
}
